-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 16:08:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbchat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbchat` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `dbchat` ;

-- -----------------------------------------------------
-- Table `dbchat`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  `nombre` VARCHAR(150) NULL,
  `apellido` VARCHAR(150) NULL,
  `tipo` BIT(1) NULL,
  `estiloaprendizaje` VARCHAR(30) NULL,
  `auth_key` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`asignaturas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`asignaturas_docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`asignaturas_docentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `asignaturas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignaturas-docentes_usuarios_idx` (`usuarios_id` ASC),
  INDEX `fk_asignaturas-docentes_asignaturas1_idx` (`asignaturas_id` ASC),
  CONSTRAINT `fk_asignaturas-docentes_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `dbchat`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignaturas-docentes_asignaturas1`
    FOREIGN KEY (`asignaturas_id`)
    REFERENCES `dbchat`.`asignaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`tareas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripción` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`metodos_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`metodos_formacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` TINYINT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `cantidadintegrantes` TINYINT NULL,
  `asignaturas_id` INT NOT NULL,
  `metodos_formacion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupos_asignaturas1_idx` (`asignaturas_id` ASC),
  INDEX `fk_grupos_metodos_formacion1_idx` (`metodos_formacion_id` ASC),
  CONSTRAINT `fk_grupos_asignaturas1`
    FOREIGN KEY (`asignaturas_id`)
    REFERENCES `dbchat`.`asignaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_metodos_formacion1`
    FOREIGN KEY (`metodos_formacion_id`)
    REFERENCES `dbchat`.`metodos_formacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`grupos_alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`grupos_alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `grupos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grupos_alumnos_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_grupos_alumnos_grupos1_idx` (`grupos_id` ASC),
  CONSTRAINT `fk_grupos_alumnos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `dbchat`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupos_alumnos_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `dbchat`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`tareas_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`tareas_year` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asignaturas_id` INT NOT NULL,
  `tareas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tareas_year_asignaturas1_idx` (`asignaturas_id` ASC),
  INDEX `fk_tareas_year_tareas1_idx` (`tareas_id` ASC),
  CONSTRAINT `fk_tareas_year_asignaturas1`
    FOREIGN KEY (`asignaturas_id`)
    REFERENCES `dbchat`.`asignaturas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_year_tareas1`
    FOREIGN KEY (`tareas_id`)
    REFERENCES `dbchat`.`tareas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`chats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NULL,
  `fecha` DATETIME NULL,
  `grupos_id` INT NOT NULL,
  `tareas_year_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chats_grupos1_idx` (`grupos_id` ASC),
  INDEX `fk_chats_tareas_year1_idx` (`tareas_year_id` ASC),
  CONSTRAINT `fk_chats_grupos1`
    FOREIGN KEY (`grupos_id`)
    REFERENCES `dbchat`.`grupos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chats_tareas_year1`
    FOREIGN KEY (`tareas_year_id`)
    REFERENCES `dbchat`.`tareas_year` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`sentencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`sentencias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sentencia` VARCHAR(255) NULL,
  `usuarios_id` INT NOT NULL,
  `chats_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sentencias_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_sentencias_chats1_idx` (`chats_id` ASC),
  CONSTRAINT `fk_sentencias_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `dbchat`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sentencias_chats1`
    FOREIGN KEY (`chats_id`)
    REFERENCES `dbchat`.`chats` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`sentencias_apertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`sentencias_apertura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sentencia` VARCHAR(255) NULL,
  `atributo` TINYINT NULL,
  `habilidad` TINYINT NULL,
  `subhabilidad` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbchat`.`sentencias_con_sentencias_apertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbchat`.`sentencias_con_sentencias_apertura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sentencias_id` INT NOT NULL,
  `sentencias_apertura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sentencias_con_sentencias_apertura_sentencias1_idx` (`sentencias_id` ASC),
  INDEX `fk_sentencias_con_sentencias_apertura_sentencias_apertura1_idx` (`sentencias_apertura_id` ASC),
  CONSTRAINT `fk_sentencias_con_sentencias_apertura_sentencias1`
    FOREIGN KEY (`sentencias_id`)
    REFERENCES `dbchat`.`sentencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sentencias_con_sentencias_apertura_sentencias_apertura1`
    FOREIGN KEY (`sentencias_apertura_id`)
    REFERENCES `dbchat`.`sentencias_apertura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
